### PR TITLE
v0.2.1: Remove dependency on semtonotes-client

### LINKED ISSUE #1: Resolve peerDependencies
Hi! I'm trying to install this package with npm v7, but there seems to be a bidirectional version conflict between -utils and -client. The [v0.2.5 client](https://github.com/UB-Heidelberg/SemToNotes/blob/develop/client/package.json) seems to not have any peerDependencies, so could we upgrade to that, and maybe even allow SemVer-compatible updates?
Does it even have to be a peer dependency or can we make it a regular one?

### PR DESCRIPTION
**Pull request by mk-pmb**
Fixes #1.

### CODE REVIEW

**Comment by mk-pmb** [comment]
@kba Pinging you because I'm not sure if GitHub notified you.

**Comment by kba** [comment]
I have invited you to the repo, I can also give you the rights to publish to npm.js for the semtonotes/anno repos, so I am not the gatekeeper for your developments. Can you give me a list of the projects you need access for?

**Comment by mk-pmb** [comment]
Indeed, now I see I can merge here. Seems I just had my browser misconfigured and therefor didn't notice I should be able to. Please add me (npm user: mk-pmb) as owner of the npm package as well.
Edit: Currently `semtonotes-utils` is the only package I see a need for to publish on npm.

**Comment by kba** [comment]
> Edit: Currently `semtonotes-utils` is the only package I see a need for to publish on npm.

You should have write access to it now.

**Comment by mk-pmb** [comment]
It works, thanks! I just published [v0.2.1](https://www.npmjs.com/package/semtonotes-utils/v/0.2.1).

**Pull request merged**
